services:
  - name: jiyi-zhumeng-backend
    type: web
    plan: free
    runtime: node
    repository: git@github.com:zxs20050325-creator/my-shop-demo.git
    rootDirectory: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production

  - name: jiyi-zhumeng-frontend
    type: web
    plan: free
    runtime: static
    repository: git@github.com:zxs20050325-creator/my-shop-demo.git
    rootDirectory: frontend
    buildCommand: echo "No build required"
    startCommand: echo "Starting static server"
    envVars:
      - key: NODE_ENV
        value: production