services:
  - name: shop-backend
    type: web
    plan: free
    runtime: node
    repository: git@github.com:zxs20050325-creator/my-shop-demo.git
    rootDirectory: backend
    buildCommand: npm install
    startCommand: node index.js  # 修改：从 server.js 改为 index.js
    envVars:
      - key: NODE_ENV
        value: production

  - name: shop-frontend
    type: static
    plan: free
    runtime: static
    repository: git@github.com:zxs20050325-creator/my-shop-demo.git
    rootDirectory: frontend
    buildCommand: echo "No build required"
    staticPublishPath: ./
    envVars:
      - key: NODE_ENV
        value: production